# Generated by Django 2.2.2 on 2019-06-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpostdevelopment',
            name='tenure',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
