# Generated by Django 2.2.2 on 2019-06-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20190621_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpostdevelopment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
