# Generated by Django 2.2.2 on 2019-06-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_listingpostdevelopment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpostdevelopment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
