# Generated by Django 2.2.2 on 2019-08-10 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20190621_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpostdevelopment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
