# Generated by Django 2.2.2 on 2019-08-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_listingpostdevelopment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingpostdevelopment',
            name='date',
        ),
    ]
