# Generated by Django 2.2.2 on 2019-08-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_listingpostdevelopment_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpostdevelopment',
            name='dropdown',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
