# Generated by Django 2.2.2 on 2019-09-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_listingpostdevelopment_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpostdevelopment',
            name='date',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
