# Generated by Django 2.2.2 on 2019-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_listingpostdevelopment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingpostdevelopment',
            name='date',
        ),
        migrations.AddField(
            model_name='listingpostdevelopment',
            name='daee',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
