# Generated by Django 2.2.2 on 2019-09-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_listingpostdevelopment_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpostdevelopment',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
