# Generated by Django 2.2.2 on 2019-09-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_auto_20190919_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpostdevelopment',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='listingpostdevelopment',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
