# Generated by Django 2.2.2 on 2019-09-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_auto_20190919_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpostdevelopment',
            name='latitude',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='listingpostdevelopment',
            name='longitude',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
