# Generated by Django 2.2.2 on 2019-06-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='default', max_length=15),
            preserve_default=False,
        ),
    ]
